server:
  shutdown: graceful
  port: 8080
spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: U9f4wG5wrk1cOhtBh0T2l4BRY8B0/j6H7vRvXmvqMhOcUQstYjAb648Nkr2dDMFn
  expiration-time: 3600000 # 1시간: 1 * 60 * 60 * 1000 = 3600000
  refresh-expiration-time: 10800000 # 3시간: 3 * 60 * 60 * 1000 = 3600000

---
